#!/bin/bash
APP_HOME=.; export APP_HOME
JAVA_OPTS=-Xms64M -Xmx256M
#JAVA_OPTS=$JAVA_OPTS -DDEBUG 
export JAVA_OPTS

CLASSPATH=
CLASSPATH=$APP_HOME/lib/jcommon-1.0.22.jar:$CLASSPATH
CLASSPATH=$APP_HOME/lib/jfreechart-1.0.17.jar:$CLASSPATH
CLASSPATH=$APP_HOME/lib/vawr.jar:$CLASSPATH
CLASSPATH=$APP_HOME/lib/vawr-o.jar:$CLASSPATH
CLASSPATH=$APP_HOME/lib/vawr-utils.jar:$CLASSPATH
CLASSPATH=$APP_HOME/lib/ojdbc5.jar:$CLASSPATH
export CLASSPATH

java $JAVA_OPTS -DAPP_HOME=$APP_HOME org.altaprise.vawr.ui.RootFrame
