#!/bin/bash
APP_HOME=.; export APP_HOME
# Java 8.
export JAVA_HOME=/e/jdk-1.8.0-241
JAVA_OPTS="-Xms64M -Xmx512M"
#JAVA_OPTS=$JAVA_OPTS -DDEBUG 
export JAVA_OPTS

CLASSPATH=
CLASSPATH=$APP_HOME/lib/jcommon-1.0.22.jar:$CLASSPATH
CLASSPATH=$APP_HOME/lib/jfreechart-1.0.17.jar:$CLASSPATH
CLASSPATH=$APP_HOME/lib/vawr.jar:$CLASSPATH
CLASSPATH=$APP_HOME/lib/vawr-o.jar:$CLASSPATH
CLASSPATH=$APP_HOME/lib/vawr-utils.jar:$CLASSPATH
CLASSPATH=$APP_HOME/lib/ojdbc5.jar:$CLASSPATH
export CLASSPATH

PATH=$JAVA_HOME/bin:$PATH

java $JAVA_OPTS -DAPP_HOME=$APP_HOME org.altaprise.vawr.ui.RootFrame
